//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialDos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recepcion
    {

       
        public int RecId { get; set; }
        [Display(Name = "Rut Cliente")]
        public string CliRut { get; set; }
        [Display(Name = "Laboratorio")]
        public Nullable<int> LabId { get; set; }
        [Display(Name = "Folio")]
        public Nullable<int> RecFolio { get; set; }

        //intentar poner el largo maximo  para la fecha de recepcion
        [Display(Name = "Fecha de recepción")]
        public Nullable<System.DateTime> RecFechaRecepcion { get; set; }
        [Display(Name = "Fecha de entrega")]
        public Nullable<System.DateTime> RecFechaEntrega { get; set; }

        [Display(Name = "Localidad")]
        public string RecLocalidad { get; set; }

        [Display(Name = "Cantidad Muestras")]
        public Nullable<int> RecCantidadMuestras { get; set; }

        [Display(Name = "Rut Cliente")]
        public virtual Clientes Clientes { get; set; }
        [Display(Name = "Laboratorio")]
        public virtual Laboratorios Laboratorios { get; set; }
    }
}
